strigo/strigo-sdk

src/modules/events-storage/events-storage.ts, src/strigo/index.ts
HOST listens to changes on events storage, postsMessage to Strigo's iframe and pops the event out
=> Strg 2051 sdk host read from local storage and

.prettierrc.json, src/modules/config/config.ts, src/modules/events-storage/events-storage.ts, src/modules/events-storage/events-storage.types.ts, src/modules/storage-utils/storage-utils.types.ts, src/strigo/index.ts
Y no template @DvirMalka ?
Added events storage as an array of events in local storage.
Currently create the write operation of events aka sendEvent
Next step - listen to local storage (on the Host's side) and postMessage to Strigo
=> Add events storage

package-lock.json, package.json, purge-jsdelivr.js
Add a tool to invalidate the CDN served files. since JSDelivr won't do it for us
=> Add jsdelivr purge CDN

services/logger.ts, src/modules/events-sender/events-sender.ts, src/modules/events-storage/events-storage.ts, src/modules/storage-utils/storage-utils.ts, src/strigo/index.ts
Log all the things!
Dedicated to @guzzur and @DvirMalka
=> Logger 4 da win

README.md
Instead of presenting this as part of the acceptance test, I just issued my notes as a PR.
=> Change wording a bit.

package-lock.json
The package-lock.json was mistakenly created by a wrong version of npm (probably someone didn't run `nvm install`/`nvm use` before installing package/s). This fixes it.
=> Update package-lock to v2

README.md, purge-jsdelivr.js, src/modules/config/config.types.ts
This lints unlinted files (including README.md)
=> Prettify everything

README.md
Add send event functionality to the readme
=> Add challenge events documentation

src/modules/widgets/iframe.ts, src/styles/strigo.css
Change gutter style
List of related documents
List of implemented tests
Add screenshots before and after
=> Change gutterSize

services/logger.ts, src/modules/config/config.types.ts, src/strigo/index.ts
Enabling to send logs to a configurable EP
Pull details (URL and token) from EP, send logs there and additionally log to console
EP PR
https://github.com/strigo/strigo-app/pull/3519
=> Logger singelton to log to EP

.circleci/config.yml, dist/development/strigo.sdk.js, package-lock.json, package.json, src/modules/events-sender/events-sender.ts, src/modules/events-storage/events-storage.ts, src/modules/listeners/listeners.ts, src/modules/storage-utils/storage-utils.ts, src/modules/widgets/iframe.ts, src/modules/widgets/overlay.ts, src/modules/widgets/widget-factory.ts, src/services/logger.ts, src/strigo/globals.d.ts, src/strigo/index.ts, tsconfig.json
1. Add typescript configuration, typescript package and add its validation to CI process.
3. Move logger to the src folder to place all of the code inside the same folder and make typescript targeting simple.
=> Strg 2375 typescript validation

dist/development/strigo.sdk.js, src/modules/widgets/overlay.ts
=> [semver:patch] Add overlay widget close log

dist/development/strigo.sdk.js, src/modules/assessment-recorder/assessment-recorder.ts, src/modules/session/session.types.ts, src/modules/url/url.ts, src/strigo.sdk.ts
Add persistency recorder using session params
=> [semver:patch] Add persistency recorder

src/modules/listeners/listeners.ts, src/modules/widgets/overlay.ts
=> [semver:patch] Remove document observer

esbuild-dev.js
=> Remove unnecessary sdk line

src/modules/widgets/overlay.ts
=> [semver:patch] bump version

src/modules/widgets/iframe.ts, src/modules/widgets/overlay.ts
=> Send dockable as boolean

src/modules/assessment-recorder/assessment-recorder.ts
Persist recorder window id on navigation.
=> Persist recorder window id on navigation

src/modules/no-code-assessment/no-code-assessment.ts
=> Add a version for the debug UI 

dist/development/strigo.sdk.js, src/modules/assessment-recorder/assessment-recorder.ts, src/modules/assessment-recorder/assessment-recorder.types.ts, src/modules/url/url.ts
Remove Strigo related params from the returned recording url in recorded assessment obj.
=> Remove Strigo related params from the returned recording url

dist/development/strigo.sdk.js, src/modules/assessment-recorder/assessment-recorder.ts, src/modules/element-selector/element-selector.js, src/strigo/index.ts, src/strigo/types.ts
Add aborting action when 'esc' to the element selection
=> Add aborting action to element selection

src/modules/element-selector/element-selector.js
=> Create version 1.1.39

src/modules/no-code-assessment/no-code-assessment.ts
=> Create version v.1.1.48

.circleci/config.yml, src/modules/no-code-assessment/no-code-assessment.ts
=> Fix version v1.1.48

src/styles/strigo-academy-hat.scss
=> Optimize loader look and feel
